# Generated by Django 3.2.9 on 2021-11-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peticion',
            fields=[
                ('id_usuario', models.IntegerField()),
                ('num_radicado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateField()),
                ('respuesta_admin', models.BooleanField()),
                ('desc_respuesta', models.CharField(max_length=200)),
                ('fecha_respuesta', models.DateField()),
                ('usuario_agrado', models.BooleanField()),
                ('hay_reclamo', models.BooleanField()),
                ('reclamo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id_usuario', models.IntegerField()),
                ('num_radicado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateField()),
                ('respuesta_admin', models.BooleanField()),
                ('desc_respuesta', models.CharField(max_length=200)),
                ('fecha_respuesta', models.DateField()),
                ('usuario_agrado', models.BooleanField()),
                ('hay_reclamo', models.BooleanField()),
                ('reclamo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReclamoP',
            fields=[
                ('num_peticion', models.IntegerField()),
                ('num_radicado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ReclamoQ',
            fields=[
                ('num_queja', models.IntegerField()),
                ('num_radicado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
